[package]
name = "mathematik"
version = "0.0.2"
entrypoint = "mathematik.typ"


description = "Ein Paket für mathematische Visualisierungen: Funktionsgraphen, Koordinatensysteme, Füllbereiche und Datensatz-Plots für den Mathematikunterricht."
license = "MIT"
repository = "https://github.com/Loewe1000/Typst-Schule"
