[package]
name = "klausurboegen"
version = "0.0.3"
entrypoint = "klausurboegen.typ"


description = "Package for klausurboegen"
license = "MIT"
repository = "https://github.com/Loewe1000/Typst-Schule"
