[package]
name = "arbeitsblatt"
version = "0.2.4"
entrypoint = "src/arbeitsblatt.typ"
authors = ["Lukas Köhl", "Alexander Schulz"]
description = "Ein umfassendes Typst-Paket zur Erstellung professioneller Arbeitsblätter für den Schulunterricht. Bietet vorgefertigte Funktionen und viele Einstellungsmöglichkeiten für Lehrer zur effizienten Gestaltung von Unterrichtsmaterialien."
license = "MIT"
repository = "https://material.mathemensch.de/files/typst/arbeitsblatt-manual.pdf"
exclude = ["docs"]
keywords = [
    "ab",
    "arbeitsblatt",
    "lehrer",
]
categories = ["office", "layout", "components"]
disciplines = ["education", "mathematics", "physics", "computer-science"]

[template]
path = "template"
entrypoint = "ab.typ"
thumbnail = "thumbnail.png"