[package]
name = "arbeitsblatt"
version = "0.2.0"
entrypoint = "arbeitsblatt.typ"
exclude = ["/assets/*", "*.pdf", "example.typ"]
compiler = "0.12"

description = "Package for arbeitsblatt"
license = "MIT"
